### ISSUE TITLE
Can't edit

### ISSUE THREAD

**Issue by karthage-spartacus** [aubreypwd/easy-photo-album#4]
Hello.
Why can't we edit the EPA_Renderer.php & the EPA_insert_album.php ?

**Comment by aubreypwd** [comment]
Not sure what you mean?

**Comment by karthage-spartacus** [comment]
Well when I edit the plugin wordpress just ignore the changes and keep using the original version.
I suppose that it came from the plugin itself; it never happened before.

**Comment by aubreypwd** [comment]
Sorry, but editing the plugin directly is not suggested as automated updates will overwrite your changes.
